---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: sicruse.powerline-fonts
      when: configure_powerline
      tags: ['powerline-fonts']
      
    # https://opensource.com/article/19/5/python-3-default-mac
    - role: markosamuli.pyenv
      tags: ['pyenv']
      # Test Fonts by changing iTerm to Menlo
      # Then echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"

    # - role: geerlingguy.mas
    #   when: mas_installed_apps
    #   tags: ['mas']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - include_tasks: tasks/terminal.yml
      when: configure_terminal

    - include: tasks/oh-my-zsh-setup.yml
      when: configure_zsh
      tags: ['ohmyzsh']

    - include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
