---
- name: Clone oh-my-zsh repo
  git: repo=https://github.com/ohmyzsh/ohmyzsh.git dest="{{general.local_home}}/.oh-my-zsh"

# Plugins
- name: Clone zsh-history-substring-search
  git: repo=https://github.com/zsh-users/zsh-history-substring-search dest={{general.local_home}}/.oh-my-zsh/custom/plugins/zsh-history-substring-search

- name: Clone zsh-syntax-highlighting
  git: repo=https://github.com/zsh-users/zsh-syntax-highlighting.git dest={{general.local_home}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Clone zsh-autosuggestions
  git: repo=https://github.com/zsh-users/zsh-autosuggestions dest={{general.local_home}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions

# Themes
- name: Install powerlevel10k
  git: repo=https://github.com/romkatv/powerlevel10k.git dest={{general.local_home}}/.oh-my-zsh/custom/themes/powerlevel10k depth=1

# - name: Set zsh as default shell
#   shell: chsh -s $(which zsh)
- name: Set zsh as default shell
  user:
    name: "{{general.user_name}}"
    shell: /bin/zsh
  become: true
  when: zsh_change_user_shell